name: Build and Test
on:
  push:
    branches: [ '*', 'series/*' ]
  pull_request:
    types: [ synchronize ]

jobs:
  test:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    if: "!contains(github.event.head_commit.message, 'ci skip')"
    steps:
    - uses: actions/checkout@v2
    - uses: coursier/cache-action@v5
    - name: Set up JDK
      uses: olafurpg/setup-scala@v10
      with:
        java-version: adopt@1.11
    - name: Scalafmt Check
      run: sbt scalafmtCheckAll
    - name: "2.13 Test"
      run: sbt "++ 2.13.5 test"
    - name: "2.12 Test"
      run: sbt "++ 2.12.13 test"
